version: "3.3"
services:
    tensorflow_keras:
        build:
          context: ./tensorflow_keras
          dockerfile: Dockerfile
        ports:
          - "8888:8888"
          - "6006:6006"
        volumes:
          - .:/usr/src/app
        runtime: nvidia