version: '2.3'
services:
  tensorflow_keras:
    build:
      context: ./tensorflow_keras
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "6006:6006"
      - "22:22"
    runtime: nvidia
    command: /bin/bash