version: "3"
services:
    app:
        build:
          dockerfile: Dockerfile
        ports:
          - "8888:8888"
          - "6006:6006"
        volumes:
          - .:/usr/src/app
        runtime: nvidia